### ISSUE TITLE
Cursor doesn't return to previous shape when switching between tmux panes/windows

### ISSUE THREAD

**Issue by jmolero** [chitoku-k/zsh-togglecursor#1]
Hi. Thanks for this plugin!

It works really well but seems it doesn't reflect the current mode if switching back from a pane that didn't have the same mode enabled.

Any idea on how to fix this?

**Comment by chitoku-k** [comment]
@jmolero Thank you for being interested in this plugin.

Unfortunately this plugin does nothing special for tmux handling except for quoting escape sequences and it causes unexpected cursor shape. There is no certain method for programs running inside tmux to know when tmux pane is changed. One solution I might suggest you give a shot is use `tmux hooks` which can be found [here](http://man.openbsd.org/OpenBSD-current/man1/tmux.1#HOOKS); however, it must be tricky as they do not provide any explicit hooks which are raised when the current pane be changed.

**Comment by jmolero** [comment]
Thanks chitoku for the link. I found solution that works for me. I have this now in my zshrc:

```
zle-line-init () {
  zle -K viins
  echo -ne "\033[5 q"
}
zle -N zle-line-init
zle-keymap-select () {
  if [[ $KEYMAP == vicmd ]]; then
    printf "\033[2 q"
  else
    printf "\033[5 q"
  fi
}
zle -N zle-keymap-select
```

I got the code [here](http://micahelliott.com/posts/2015-07-20-vim-zsh-tmux-cursor.html) but had to change it a bit. Seems that the "if [[ -z $TMUX ]]; then" is no longer needed.

**Comment by chitoku-k** [comment]
I finally figured out what happens. tmux has to be configured properly so that it overrides terminal sequences of cursor shape and manage by tmux. It seems that you either have something like as follows in your `tmux.conf` or your terminal behaves so by default:

```tmux
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
```

This line was taken from [FAQ · neovim/neovim Wiki](https://github.com/neovim/neovim/wiki/FAQ) and it works like a charm if only zsh-togglecursor removes tmux support (as neovim does).

**Comment by jmolero** [comment]
Yes, I forgot to mention I have this overrides setting in tmux.conf.

Thanks for your support!
